### ISSUE TITLE
Problem with installating clustifyrdatahub

### ISSUE THREAD

**Issue by mihem** [rnabioco/clustifyrdatahub#2]
Great idea to create a package that allows easy integration with clustifyr (scRNAseq on Bioconductor has something similar and it has even more datasets, but the packages does not work nicely with clustifyr ... which is much faster than SingleR).

Unfortunately, installing the packages as described does not work:
```
BiocManager::install("clustifyrdatahub")
Warning message:
package ‘clustifyrdatahub’ is not available (for R version 4.0.2)
```
On Bioconductor instructions tell you to install using devel version .. but that requires upgrading all bioconductor packages to devel, which I would like to avoid. 

Using install_github:

`remotes::install_github("rnabioco/clustifyrdatahub")`
stops with

`Error: package or namespace load failed for ‘clustifyrdatahub’:
 .onLoad failed in loadNamespace() for 'clustifyrdatahub', details:
  call: FUN(X[[i]], ...)
  error: ‘ref_MCA’ not found in ExperimentHub
`

Thanks for your help!
Mischko

**Comment by raysinensis** [comment]
Hi Mischko,

`clustifyrdatahub` is simply creating accessors to the data. The issue appears to be that ExperimentHub/AnnotationHub restricts the database by Bioconductor version internally. Simply updating those packages to the devel version also doesn't work (snapshotdate() still returns 2020-4-27 of the hub, the release version). I'm not sure there is a clean/easy way to install it without updating Bioconductor, which is annoying.

One alternative we offer is direct .rda downloads, here: https://rnabioco.github.io/clustifyrdata/articles/download_refs.html.

Also, please let us know what the issue is between `clustifyr` and `scRNAseq` on Bioconductor, so we can look into fixing/improving things.

**Comment by mihem** [comment]
Hey raysinensis,
thanks for your fast reply.

Ah, I didn't know about clustifyrdata. To be honest I don't really understand the difference between clustifyrdatahub and clustifyrdata. But clustifyrdata works like a charme. 

Concerning clustifyrdatahub: Would be of course great if it just worked with Bioconductor, but if it doesn't  it would be nice if installation via install_github would work ... but at least for my needs clustifyrdata is all I need. Although 42 annotated datasets is quite impressive, there are so many organs, specialized cell types that it would make sense to have even more datasets (e.g. right now I am interested in different sort of microglia/brain associated macrophages and I barely find the annotation microglia ;))

Thanks,
Mischko
